### ISSUE TITLE
Support for already open file pointers

### ISSUE THREAD

**Issue by pwoods25443** [SkyTruth/gpsdio#104]
It would be helpful to be able to use gpsdio with an already open stream such as one might get from stdin

in that case there is no file extension, so the driver parameter would be required

use would be something like this:
```
def parse_already_open_text_file (fp, driver):
    with gpsdio.open(fp, driver) as src:
        for msg in src:
            print msg

parse_already_open_text_file (sys.stdin, 'somedriver')
```

**Comment by geowurster** [comment]
@pwoods25443 this is already supported for at least [MsgPack](https://github.com/SkyTruth/gpsdio/blob/master/gpsdio/drivers.py#L216-L219) and [NewlineJSON](https://github.com/geowurster/NewlineJSON/blob/master/newlinejson/core.py#L56-L61), although I'm not sure if its tested for MsgPack.

This has to be handled at the driver level in case the underlying library handles file opening through some C interface (like GDAL) or DB connector string (like psycopg2) or something else.

**Comment by pwoods25443** [comment]
@geowurster can you share a code example?  I don't see any way that this could work going through gpsdio.open(), so maybe I have to work directly with the driver?

**Comment by geowurster** [comment]
@pwoods25443 _tl;dr_

- I need more info about what you would like to be able to do.  You say "text file" so do you mean an uncompressed file containing newline JSON?
- Yes you can do it with the drivers - see example at the very bottom.
- We can't operate on arbitrary open files because we don't know whats in them.
- This isn't something `gpsdio.open()` should be responsible for but it is a feature we need and it should be handled by the drivers and/or helper functions.

---

After putting together the info below my initial impression is that this isn't something `gpsdio.open()` should handle.  It's job is to take a file path (or URL, connection string, etc), an IO mode (r, w), instantiate the necessary drivers, and give the user an instance of `gpsdio.core.Stream()` that they can interact with.  This is the core object that handles all of the message validation but it needs some small changes and helper functions to make it easier to pass data from various in-memory sources through it.  We can't just operate on arbitrary open files because we don't know whats in them.  Consider newline JSON vs MsgPack - we read both line by line but each line has to go through a separate process and we can't direct that process unless we know what kind of open file we have.  To solve that problem we're back at the driver implementation, which can decide if it can handle an open file or not.

This next part is more for future me, although it contains the code examples you requested, but I looked through the source, tested some examples and found that this works, but only in certain cases.  For example, this does not work:

```python
with gzip.open('sample-data/types.msg.gz') as f, gpsdio.open(f, compression="GZIP", driver="MsgPack") as src:
    print(next(src))

# TRACEBACK

Traceback (most recent call last):
  File "buh.py", line 18, in <module>
    print(next(src))
  File "/Users/wursterk/github/gpsdio/gpsdio/core.py", line 175, in next
    raise Exception("%s: %s: %s\n%s" % (getattr(self._stream, 'name', 'Unknown'), type(e), e, "    " + traceback.format_exc().replace("\n", "\n    ")))
Exception: sample-data/types.msg.gz: <type 'exceptions.ValueError'>: Seek from end not supported
    Traceback (most recent call last):
      File "/Users/wursterk/github/gpsdio/gpsdio/core.py", line 164, in next
        loaded = line = next(self._stream)
      File "/Users/wursterk/github/gpsdio/gpsdio/base.py", line 111, in next
        return next(self.stream)
      File "msgpack/_unpacker.pyx", line 459, in msgpack._unpacker.Unpacker.__next__ (msgpack/_unpacker.cpp:459)
      File "msgpack/_unpacker.pyx", line 380, in msgpack._unpacker.Unpacker._unpack (msgpack/_unpacker.cpp:380)
      File "msgpack/_unpacker.pyx", line 365, in msgpack._unpacker.Unpacker.read_from_file (msgpack/_unpacker.cpp:367)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 268, in read
        self._read(readsize)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 296, in _read
        self.fileobj.seek(0, 2)     # Seek to end of file
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 429, in seek
        raise ValueError('Seek from end not supported')
    ValueError: Seek from end not supported
```

But the code below does.  Using `False` for `compression` and `driver` intentionally disables instantiating a compression and IO driver but may not be permanent behavior, especially after I looked into this specific issue.

```python
with gzip.open('sample-data/types.msg.gz') as f, gpsdio.open(f, compression=False, driver=False) as src:
    print(next(src))
```

Theoretically the code below should work for newline JSON for the exact same reason, except that the IO driver building isn't disabled when it should be and `newlinejson.core.Stream()` doesn't have a `name` property.

```python
with nlj.open('sample-data/types.json') as f, gpsdio.open(f, driver=False, compression=False) as src:
    print(next(src))

# TRACEBACK

Traceback (most recent call last):
  File "buh.py", line 9, in <module>
    with nlj.open('sample-data/types.json') as f, gpsdio.open(f, driver=False, compression=False) as src:
  File "/Users/wursterk/github/gpsdio/gpsdio/core.py", line 86, in open
    io_driver = drivers.detect_file_type(getattr(path, 'name', path))
  File "/Users/wursterk/github/gpsdio/gpsdio/drivers.py", line 59, in detect_file_type
    for ext in path.split('.')[-2:]:
AttributeError: 'Stream' object has no attribute 'split'
```

This also works:

```python
import gpsdio.core
from gpsdio.drivers import MsgPack, GZIP

with gpsdio.core.Stream(MsgPack(GZIP('sample-data/types.msg.gz'))) as src:
    print(next(src))
```

**Comment by geowurster** [comment]
Looks like the changes really need to happen in the drivers, so supporting this is possible.  If the drivers receive the object they would normally be return in `Driver.open()`, they just need to just that object.
