### ISSUE TITLE
nosetest with executable tests

### ISSUE THREAD

**Issue by schwehr** [SkyTruth/gpsdio#147]
This is in the "I can't remember where this came up" category.

I remember someone telling me that nose rejects tests that are marked executable, which makes it annoying if want people to be able to just run a test file by specifying it on the command line.  I believe this will fix it.

Add this to setup.cfg:

    [nosetests]
    exe=True

**Comment by geowurster** [comment]
@schwehr Thanks for the recommendation, but we're using [`py.test`](http://pytest.org/latest/), because it gives better failure messages and has fixtures, which `nose` can't emulate, so we can't support both.

To run a single test file:  `py.test tests/test_base.py`

To run a single test function: `py.test tests/test_base.py::test_wrong_mode`

**Comment by schwehr** [comment]
Ok.  Thanks.  Updated https://github.com/schwehr/libais/issues/113
